import { createHash, randomUUID } from 'node:crypto';import { createReadStream } from 'node:fs';import { mkdir, open, rename, rm, stat } from 'node:fs/promises';import { dirname,join } from 'node:path';
const DIGEST_RE=/^sha256:([a-f0-9]{64})$/;export const DEFAULT_MAX_UPLOAD=20*1024*1024;
export function safeName(name){const x=String(name||'artifact.bin').normalize('NFKC').replace(/[\r\n\\/\0]/g,'_').replace(/[^\p{L}\p{N}._ -]/gu,'_').trim();return (x||'artifact.bin').slice(0,160);}
export function blobPath(root,digest){const m=DIGEST_RE.exec(digest);if(!m)throw new Error('invalid digest');return join(root,'blobs','sha256',m[1].slice(0,2),m[1]);}
async function hashFile(path){const h=createHash('sha256');for await(const c of createReadStream(path))h.update(c);return `sha256:${h.digest('hex')}`;}
export class ArtifactService{
 constructor(store,dataRoot,{maxUploadBytes=DEFAULT_MAX_UPLOAD}={}){this.store=store;this.dataRoot=dataRoot;this.maxUploadBytes=maxUploadBytes;}
 async init(){await mkdir(join(this.dataRoot,'tmp'),{recursive:true});await mkdir(join(this.dataRoot,'blobs','sha256'),{recursive:true});return this;}
 list(){return this.store.snapshot().artifacts;}
 get(id){return this.store.snapshot().artifacts.find(x=>x.id===id)||null;}
 stats(){const s=this.store.snapshot();const unique=new Map();for(const a of s.artifacts)unique.set(a.digest,a.size);return {...s.stats,records:s.artifacts.length,uniqueBlobs:unique.size,logicalBytes:s.artifacts.reduce((n,a)=>n+a.size,0),physicalBytes:[...unique.values()].reduce((n,x)=>n+x,0)};}
 async ingest(req,{name,mediaType}){const clean=safeName(name);const type=(String(mediaType||'application/octet-stream').split(';')[0]||'application/octet-stream').slice(0,120);const tmp=join(this.dataRoot,'tmp',`${process.pid}-${Date.now()}-${randomUUID()}.part`);const fh=await open(tmp,'wx',0o600);let bytes=0;const hash=createHash('sha256');try{for await(const chunk of req){bytes+=chunk.length;if(bytes>this.maxUploadBytes){const e=new Error(`artifact exceeds ${this.maxUploadBytes} bytes`);e.status=413;throw e;}hash.update(chunk);await fh.write(chunk);}await fh.sync();}catch(e){await fh.close().catch(()=>{});await rm(tmp,{force:true});throw e;}await fh.close();const digest=`sha256:${hash.digest('hex')}`;const target=blobPath(this.dataRoot,digest);await mkdir(dirname(target),{recursive:true});let dedup=false;try{await stat(target);dedup=true;await rm(tmp,{force:true});}catch(e){if(e.code!=='ENOENT')throw e;await rename(tmp,target);}const now=new Date().toISOString();const artifact={id:`artifact_${randomUUID()}`,ref:`artifact://sha256/${digest.slice(7)}`,digest,name:clean,mediaType:type,size:bytes,createdAt:now,verifiedAt:null};await this.store.mutate(s=>{s.artifacts.unshift(artifact);s.stats.uploads++;if(dedup)s.stats.dedupHits++;s.activity.unshift({id:randomUUID(),at:now,type:dedup?'artifact.referenced_existing_blob':'artifact.stored',subject:artifact.id,digest,size:bytes});s.activity=s.activity.slice(0,500);});return {...artifact,deduplicated:dedup};}
 async verify(id){const a=this.get(id);if(!a)return null;const actual=await hashFile(blobPath(this.dataRoot,a.digest));const ok=actual===a.digest;const at=new Date().toISOString();await this.store.mutate(s=>{const x=s.artifacts.find(v=>v.id===id);if(x&&ok)x.verifiedAt=at;s.stats.verifications++;s.activity.unshift({id:randomUUID(),at,type:ok?'artifact.verified':'artifact.corrupt',subject:id,expected:a.digest,actual});});return {ok,artifactId:id,expected:a.digest,actual,verifiedAt:at};}
 async remove(id){let removed=null,last=false;await this.store.mutate(s=>{const i=s.artifacts.findIndex(x=>x.id===id);if(i<0)return;removed=s.artifacts[i];s.artifacts.splice(i,1);last=!s.artifacts.some(x=>x.digest===removed.digest);s.stats.deletes++;s.activity.unshift({id:randomUUID(),at:new Date().toISOString(),type:'artifact.record_deleted',subject:id,digest:removed.digest,lastReference:last});});if(removed&&last)await rm(blobPath(this.dataRoot,removed.digest),{force:true});return removed?{removed:true,blobDeleted:last,digest:removed.digest}:null;}
 pathFor(a){return blobPath(this.dataRoot,a.digest);}
 activity(){return this.store.snapshot().activity.slice(0,100);}
}
