import { readFile } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';

const LOOPBACK_HOSTS=new Set(['localhost','127.0.0.1','[::1]']);
export function assertLoopbackBind(host){if(!['127.0.0.1','::1','localhost'].includes(host))throw new Error('InMyArtifact v0.1 is loopback-only');}
export function requestAllowed(req){const host=(req.headers.host||'').split(':')[0];const normalized=req.headers.host?.startsWith('[::1]')?'[::1]':host; if(!LOOPBACK_HOSTS.has(normalized))return false; const origin=req.headers.origin;if(!origin)return true;try{return LOOPBACK_HOSTS.has(new URL(origin).hostname);}catch{return false;}}
export async function readJson(req,max=64*1024){let size=0,chunks=[];for await(const c of req){size+=c.length;if(size>max){const e=new Error('request body too large');e.status=413;throw e;}chunks.push(c);}if(!size)return {};try{return JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{const e=new Error('invalid JSON');e.status=400;throw e;}}
export function json(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(body),'cache-control':'no-store','x-content-type-options':'nosniff'});res.end(body);}
const TYPES={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};
export async function staticFile(res,root,path){const rel=path==='/'?'index.html':path.replace(/^\//,'');const safe=normalize(rel);if(safe.startsWith('..'))return false;try{const data=await readFile(join(root,safe));res.writeHead(200,{'content-type':TYPES[extname(safe)]||'application/octet-stream','content-length':data.length,'x-content-type-options':'nosniff','content-security-policy':"default-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'"});res.end(data);return true;}catch(e){if(e.code==='ENOENT')return false;throw e;}}
