export function integrationReadiness() {
  return {
    status: 'phase3_resolver_registry_foundation',
    ecosystemConnected: false,
    authorityProvider: null,
    protocol: 'inmy-artifact/v1-draft',
    resolverPilot: {
      available: true,
      mode: 'pilot-read-only',
      defaultEnabled: false,
      productionAuthority: false,
      digestKnowledgeAuthorizes: false,
      directDatabaseAccess: false,
      directFilesystemPathExposure: false,
      writeOperations: false,
      persistentBindingRegistry: true,
      ownerControlledRetentionState: true,
      leaseExpiryDeletesBytes: false,
      retentionEnforcement: false,
      backgroundGc: false,
    },
    preparedCapabilities: [
      'artifact.put',
      'artifact.metadata.read',
      'artifact.bytes.read',
      'artifact.verify',
      'artifact.delete',
      'artifact.resolver.metadata.read',
      'artifact.resolver.bytes.prepare',
    ],
    activationRequirements: [
      'accepted resolver pilot contract',
      'accepted persistent product-owned binding registry',
      'InMyHub capability/authority registration',
      'retention/GC enforcement policy',
      'caller quotas/classification',
      'backup/restore/reconciliation evidence',
      'bounded consumer adoption decision',
    ],
    guarantees: [
      'opaque byte storage only',
      'content addressed with SHA-256',
      'deduplication by digest',
      'digest knowledge is never authorization',
      'resolver pilot is in-process and read-only',
      'binding registry is product-owned metadata state only',
      'expired leases never authorize automatic byte deletion',
      'no archive extraction or execution',
      'no cross-product calls',
    ],
  };
}
