export function integrationReadiness() {
  return {
    status: 'phase3_reconciliation_recovery_foundation',
    ecosystemConnected: false,
    authorityProvider: null,
    protocol: 'inmy-artifact/v1-draft',
    resolverPilot: {
      available: true,
      mode: 'pilot-read-only',
      defaultEnabled: false,
      productionAuthority: false,
      digestKnowledgeAuthorizes: false,
      directDatabaseAccess: false,
      directFilesystemPathExposure: false,
      writeOperations: false,
      persistentBindingRegistry: true,
      ownerControlledRetentionState: true,
      leaseExpiryDeletesBytes: false,
      reconciliationPlanner: true,
      reconciliationAutomaticDeletesAllowed: false,
      coldBackupRestoreEvidence: 'candidate',
      corruptionRecoveryEvidence: 'candidate',
      retentionEnforcement: false,
      backgroundGc: false,
    },
    preparedCapabilities: [
      'artifact.put',
      'artifact.metadata.read',
      'artifact.bytes.read',
      'artifact.verify',
      'artifact.delete',
      'artifact.resolver.metadata.read',
      'artifact.resolver.bytes.prepare',
    ],
    activationRequirements: [
      'accepted resolver pilot contract',
      'accepted persistent product-owned binding registry',
      'accepted backup/restore/reconciliation and corruption-recovery evidence',
      'InMyHub capability/authority registration',
      'explicit retention/GC decision with owner authority and rollback',
      'caller quotas/classification',
      'bounded consumer adoption decision',
      'measured duplicate-content/storage benefit',
    ],
    guarantees: [
      'opaque byte storage only',
      'content addressed with SHA-256',
      'deduplication by digest',
      'digest knowledge is never authorization',
      'resolver pilot is in-process and read-only',
      'binding registry is product-owned metadata state only',
      'expired leases never authorize automatic byte deletion',
      'reconciliation emits no GC candidates and grants no automatic deletion authority',
      'backup/restore treats Artifact metadata, blobs and resolver registry as one consistency unit',
      'no archive extraction or execution',
      'no cross-product calls',
    ],
  };
}
